export const QUIZ_LIST_LOADING_STARTED = 'QUIZ_LIST_LOADING_STARTED';
export const QUIZ_LIST_SUCCESS = 'QUIZ_LIST_SUCCESS';
export const QUIZ_LIST_ERROR = 'QUIZ_LIST_ERROR';

export const SET_CURRENT_QUIZ_ID = 'SET_CURRENT_QUIZ_ID';
export const QUIZ_LOADING_START = 'QUIZ_LOADING_START';
export const QUIZ_LOADING_END = 'QUIZ_LOADING_END';
export const QUIZ_SUCCESS = 'QUIZ_SUCCESS';
export const QUIZ_ERROR = 'QUIZ_ERROR';
export const RESET_QUIZ = 'RESET_QUIZ';
export const SET_ANSWER = 'SET_ANSWER';
export const FINISH_QUIZ = 'FINISH_QUIZ';
export const NEXT_QUESTION = 'NEXT_QUESTION';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_EXIT = 'LOGIN_EXIT';